title: Debasish Pattanayak
theme: jekyll-theme-minimal
logo: /debasish_photo.jpg
description: Postdoctoral Researcher </br> LUISS Guido Carli </br> <a href= "twitter.com/drdebmath">Twitter</a> </br> <a href= "https://www.linkedin.com/in/debasish-pattanayak-3750a530/">LinkedIn</a>
github:
  is_project_page: false
