title: Debasish Pattanayak
theme: jekyll-theme-minimal
logo: /debasish_photo.jpg
description: Department of Mathematics, IIT Guwahati
# social links
twitter_username: drdebmath
github_username:  drdebmath
github:
  is_project_page: false
