title: Debasish Pattanayak
theme: jekyll-theme-minimal
logo: /debasish_photo.jpg
description: Postdoctoral Researcher </br> UQO </br> <a href="https://twitter.com/drdebmath?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @drdebmath</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></br> <a href= "https://www.linkedin.com/in/debasish-pattanayak-3750a530/">LinkedIn</a> </br> <a href="./#Publications">Publications</a>
github:
  is_project_page: false
