// Generates JSON-LD (injected into index.html) + sitemap.xml from data.json.
// Run via `npm run build`. ponytail: regenerated on every build, no hand-editing.
import { readFileSync, writeFileSync } from "node:fs";

const SITE = "https://drdebmath.github.io";
const data = JSON.parse(readFileSync("data.json", "utf8"));
const a = data.about_me;

// ---- JSON-LD: Person + the publication list (good for Google Scholar / Knowledge Graph) ----
const sameAs = [a.dblp, a.google_scholar, a.orcid, a.github, a.linkedin, a.x].filter(Boolean);

const person = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: a.name,
  alternateName: a.name_odia,
  jobTitle: a.position,
  url: SITE + "/",
  image: SITE + "/debasish_photo.jpeg",
  affiliation: {
    "@type": "Organization",
    name: a.current_institution?.name,
    url: a.current_institution?.url,
  },
  sameAs,
};

const articles = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  itemListElement: data.publications.map((p, i) => ({
    "@type": "ListItem",
    position: i + 1,
    item: {
      "@type": "ScholarlyArticle",
      headline: p.title,
      author: (p.authors || []).map((name) => ({ "@type": "Person", name })),
      datePublished: String(p.year ?? ""),
      isPartOf: p.journal?.full || p.booktitle || undefined,
      ...(p.doi ? { sameAs: p.doi } : {}),
    },
  })),
};

const jsonld =
  `    <!-- SEO:JSONLD:START (generated by gen-seo.mjs — do not edit by hand) -->\n` +
  `    <script type="application/ld+json">\n${JSON.stringify(person)}\n</script>\n` +
  `    <script type="application/ld+json">\n${JSON.stringify(articles)}\n</script>\n` +
  `    <!-- SEO:JSONLD:END -->`;

let html = readFileSync("index.html", "utf8");
html = html.replace(
  /^[ \t]*<!-- SEO:JSONLD:START[\s\S]*?^[ \t]*<!-- SEO:JSONLD:END -->/m,
  jsonld,
);
writeFileSync("index.html", html);

// ---- sitemap.xml: own HTML pages + simulator pages hosted on this domain ----
const urls = new Set([
  SITE + "/",
  SITE + "/cv.html",
  SITE + "/for_students.html",
  SITE + "/publications.html",
  SITE + "/teaching.html",
  SITE + "/talks.html",
  SITE + "/timeline.html",
  SITE + "/visualizations/",
]);
for (const s of data.visualizations?.simulators || []) {
  if (s.url?.startsWith(SITE)) urls.add(s.url);
}

const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  [...urls].map((u) => `  <url><loc>${u}</loc></url>`).join("\n") +
  `\n</urlset>\n`;
writeFileSync("sitemap.xml", sitemap);

console.log(`gen-seo: ${data.publications.length} publications, ${urls.size} sitemap URLs.`);
